version: "1.0"
name: "schoolapi"
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword123
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: colegio2023
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: adminuser123
    image: mysql:5.7
    ports:
      - "3306:3306"
  api:
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword123
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: colegio2023
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: adminuser123
      MYSQL_HOST: mysql
      GUNICORN_PROCESSES: 2
      GUNICORN_THREADS: 4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home
    ports:
      - "8082:8081"
