version:  "1.0"
name: "schoolapi"
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword123
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: colegio2023
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: adminuser123
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3307:3306"