site_name: QRschool
site_url: https://github.com/selobu/qrschool
theme:
  name: material
  custom_dir: ../en/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: selobu/qrschool
repo_url: https://github.com/selobu/qrschool
edit_uri: ""
nav:
  - QRschool:
      - index.md
  - Languages:
      - en: /qrschool/
      - es: /qrschool/es/
  - Tutorial - User Guide:
      - user/index.md
      - user/qr.md
      - user/profiles.md
  - Administrator:
      - admin/index.md
      - admin/cli.md
      - admin/userprofiles.md
  - About:
      - about/index.md
      - about/license.md
      - about/contact.md
plugins:
  search: null
  markdownextradata:
    data: ../en/data
markdown_extensions:
  pymdownx.details: null
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ""
  pymdownx.tabbed:
    alternate_style: true
  attr_list: null
  md_in_html: null
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
